server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: bhnkyy20010410
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis-plus:
  type-aliases-package: com.example.demo.dao
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      id-type: AUTO
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl